version: "3.9"
services:
  db:
    image: postgres:16
    container_name: aura_db
    environment:
      POSTGRES_DB: aura
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports: ["5432:5432"]
    volumes: [db_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d aura"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer
    container_name: aura_adminer
    ports: ["8080:8080"]
    depends_on: [db]

volumes:
  db_data:
