# Generated by Django 5.1.3 on 2025-02-03 19:06

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bluetooth",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "bluetooth",
            },
        ),
        migrations.CreateModel(
            name="CoreSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "leds",
                    models.BooleanField(
                        default=False, help_text="false = off, true = on"
                    ),
                ),
                (
                    "wgt_heure",
                    models.BooleanField(
                        default=False, help_text="false = off, true = on"
                    ),
                ),
                (
                    "wgt_meteo",
                    models.BooleanField(
                        default=False, help_text="false = off, true = on"
                    ),
                ),
                (
                    "wgt_musique",
                    models.BooleanField(
                        default=False, help_text="false = off, true = on"
                    ),
                ),
            ],
            options={
                "db_table": "core_settings",
            },
        ),
        migrations.CreateModel(
            name="LedsAnimation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "leds_animation",
            },
        ),
        migrations.CreateModel(
            name="LedsPersonnalisation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "color_gestion",
                    models.JSONField(
                        default=app.models.default_color_gestion,
                        help_text="Une couleur de 0 à 100 est définie à #FFF par défaut, modifiable par l'utilisateur.",
                    ),
                ),
            ],
            options={
                "db_table": "leds_personnalisation",
            },
        ),
        migrations.CreateModel(
            name="WidgetHeure",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "personalisation",
                    models.IntegerField(
                        default=0,
                        help_text="Choisis entre les différentes personnalisations en brut",
                    ),
                ),
                ("pos_x", models.IntegerField()),
                ("pos_y", models.IntegerField()),
            ],
            options={
                "db_table": "widget_heure",
            },
        ),
        migrations.CreateModel(
            name="WidgetMeteo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "personalisation",
                    models.IntegerField(
                        default=0,
                        help_text="Choisis entre les différentes personnalisations en brut",
                    ),
                ),
                ("pos_x", models.IntegerField()),
                ("pos_y", models.IntegerField()),
            ],
            options={
                "db_table": "widget_meteo",
            },
        ),
        migrations.CreateModel(
            name="WidgetMusique",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "personalisation",
                    models.IntegerField(
                        default=0,
                        help_text="Choisis entre les différentes personnalisations en brut",
                    ),
                ),
                ("pos_x", models.IntegerField()),
                ("pos_y", models.IntegerField()),
            ],
            options={
                "db_table": "widget_musique",
            },
        ),
        migrations.CreateModel(
            name="Leds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "luminosite",
                    models.SmallIntegerField(
                        default=50, help_text="Luminosité entre 0% et 100%"
                    ),
                ),
                (
                    "reactivite",
                    models.BooleanField(
                        default=False, help_text="false = off, true = on"
                    ),
                ),
                (
                    "id_animation",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_animation",
                        help_text="Si à 0, aucune animation. Sinon, référence à une animation.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.ledsanimation",
                    ),
                ),
                (
                    "personnalisation",
                    models.ForeignKey(
                        blank=True,
                        db_column="personnalisation_id",
                        help_text="Si à 0, aucune personnalisation. Sinon, référence à une personnalisation.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.ledspersonnalisation",
                    ),
                ),
            ],
            options={
                "db_table": "leds",
            },
        ),
    ]
